apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mone.labels" . | nindent 4 }}
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      {{- include "mone.selectorLabels" "redpanda" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mone.selectorLabels" "redpanda" | nindent 8 }}
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:latest
          command:
            - redpanda
            - start
            - --smp=1
            - --memory=512M
            - --reserve-memory=0M
            - --overprovisioned
            - --node-id=0
            - --kafka-addr=PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9644
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "mone.selectorLabels" "redpanda" | nindent 4 }}
  ports:
    - name: kafka
      port: 9092
    - name: metrics
      port: 9644
