version: "3.9"

services:
  postgres: 
    image: postgres:15
    container_name: mone_postgres
    restart: always
    environment:
      POSTGRES_USER: mone
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: mone_pgbouncer
    restart: always
    depends_on:
      - postgres
    ports:
      - "6432:5432"
    environment:
      DB_USER: mone
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_NAME: mone
      POOL_MODE: session
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 20
      AUTH_TYPE: md5
      AUTH_FILE: /etc/pgbouncer/userlist.txt

  redis:
    image: redis
    container_name: mone_pubsub
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: