apiVersion: v2
name: mone
description: Full-stack centralized cryptocurrency exchange
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - crypto
  - exchange
  - cex
maintainers:
  - name: mone
